export const INVALID_EMAIL_ERR_TEXT = 'Необходимо ввести корректный адрес электронной почты'
export const INVALID_URL_ERR_TEXT = 'Некорректный адрес изображения'
export const REQUIRED_EMAIL_ERR_TEXT = 'Введите почту'
export const REQUIRED_PASSWORD_ERR_TEXT = 'Введите почту'
// export const INVALID_EMAIL_ERR_TEXT = 'Необходимо ввести корректный адрес электронной почты'